Repository nanvix/libnanvix, pull requests merged in 2020-04, with the labels that each got.

#19 [ikc] Mailbox Non-blocking Read
  src/libnanvix/ikc/mailbox.c
Labels: bug, confirmed

#20 [test] Feature: Stressful tests of local communication
  src/test/ikc.c
  src/test/kmailbox.c
  src/test/kportal.c
Labels: feature

#21 [unix] Bugfix: Insecure optimizations
  build/unix64/make/makefile.cflags
Labels: bug, confirmed

#22 [tests] Bugfix: Kmailbox Bad Mbxid
  src/test/kmailbox.c
Labels: bug, confirmed

#24 [ikc] New Communicator Get_Port Kcall
  include/nanvix/sys/noc.h
  src/libnanvix/ikc/noc.c
  src/test/kportal.c
Labels: enhancement
