Repository nanvix/libnanvix, pull requests merged in 2021-02, with the labels that each got.

#72 [ikc] Feature: Mailbox Set Remote
  include/nanvix/sys/mailbox.h
  src/libnanvix/ikc/mailbox.c
Labels: enhancement

#73 [pm] Threads Fence
  include/nanvix/runtime/fence.h
  src/libnanvix/thread/fence.c
  src/test/ikc.c
  src/test/kmailbox.c
  src/test/kportal.c
Labels: feature

#67 [pm] Mutex Extensions (issue #61)
  include/nanvix/sys/mutex.h
  src/libnanvix/thread/mutex.c
  src/test/condvar.c
  src/test/main.c
  src/test/mutex.c
  src/test/sleep.c
  src/test/test.h
Labels: enhancement

#68 [pm] Enhancement: Semaphore Extensions (issue #62)
  include/nanvix/sys/semaphore.h
  src/libnanvix/thread/semaphore.c
  src/test/main.c
  src/test/semaphore.c
  src/test/test.h
Labels: enhancement

#60 [pm] Thread return value tests
  src/test/kthread.c
Labels: feature

#77 [pm] Synchronization Condvar Release Ordering in All Platforms
  include/nanvix/sys/condvar.h
  src/libnanvix/thread/condvar.c
Labels: bug
